version: 2
jobs:
  build:
    docker:
      - image: tesyolan/coreference-resolution:latest
    steps:
      - checkout
      - run:
          name: Get Models
          command: ./install.sh
      - run:
          name: Run Tests
          command: python3.6 -m unittest test_rpc_call.TestSuiteGrpc


workflows:
  version: 2
  build_and_test:
    jobs:
      - build